### PR TITLE
Add no-multiple-empty-lines

### PR DESCRIPTION
**Pull request by gabro**
Issue #80 (partially)

## Test plan

Linto 🎉 

|     | repo                           | errors | warnings |
| :-: | :----------------------------- | :----: | :------: |
|  ✅  | buildo/aliniq                  |    0   |     0    |
|  ✅  | buildo/web-shared              |    0   |     0    |
|  ✅  | buildo/lexdoit                 |    0   |     0    |
|  ✅  | buildo/ipercron                |    0   |     0    |
|  ✅  | buildo/bobafett                |    0   |     0    |
|  ✅  | buildo/avenger                 |    0   |     0    |
|  ✅  | buildo/react-components        |    0   |     0    |
|  ✅  | buildo/rc-datepicker           |    0   |     0    |
|  ✅  | buildo/react-cookie-banner     |    0   |     0    |
|  ✅  | buildo/react-autosize-textarea |    0   |     0    |
|  ✅  | buildo/react-input-link        |    0   |     0    |
|  ✅  | buildo/react-flexview          |    0   |     0    |
|  ✅  | buildo/react-placeholder       |    0   |     0    |
|  ✅  | buildo/local-date              |    0   |     0    |
|  ✅  | buildo/formo                   |    0   |     0    |
|  ✅  | buildo/hophop                  |    0   |     0    |
|  ✅  | buildo/nemobot                 |    0   |     0    |
|  ✅  | buildo/prisma                  |    0   |     0    |
|  ✅ | buildo/pledge                  |    0   |     0   |

### CODE REVIEW

**Comment by gabro** [comment]
(did I forget any project?)

**Comment by giogonzo** [comment]
lexdoit?

**Comment by gabro** [comment]
lol, woops.

**Comment by gabro** [comment]
mm, lexdoit is a tricky one, I think I'll work on linto a little bit to make it work

**Comment by FrancescoCioria** [comment]
also:
- rc-datepicker
- react-cookie-banner
- react-autosize-textarea
- react-input-link
- react-flexview
- react-placeholder (or not :P)
- local-date
- nemobot
- prisma

PR: from the list above I would only test `nemobot` and `prisma` as they're the only ones continuosly deployed (for the other ones it's no big issue if eslint breaks)

**Comment by gabro** [comment]
Well, including all the projects above, linto produces a report in less than 40s on my machine :)

|     | repo                           | errors | warnings |
| :-: | :----------------------------- | :----: | :------: |
|  ✅  | buildo/aliniq                  |    0   |     0    |
|  ✅  | buildo/web-shared              |    0   |     0    |
|  ✅  | buildo/lexdoit                 |    0   |     0    |
|  ✅  | buildo/ipercron                |    0   |     0    |
|  ✅  | buildo/bobafett                |    0   |     0    |
|  ✅  | buildo/avenger                 |    0   |     0    |
|  ✅  | buildo/react-components        |    0   |     0    |
|  ✅  | buildo/rc-datepicker           |    0   |     0    |
|  ✅  | buildo/react-cookie-banner     |    0   |     0    |
|  ✅  | buildo/react-autosize-textarea |    0   |     0    |
|  ✅  | buildo/react-input-link        |    0   |     0    |
|  ✅  | buildo/react-flexview          |    0   |     0    |
|  ✅  | buildo/react-placeholder       |    0   |     0    |
|  ✅  | buildo/local-date              |    0   |     0    |
|  ✅  | buildo/formo                   |    0   |     0    |
|  ✅  | buildo/hophop                  |    0   |     0    |
|  ✅  | buildo/nemobot                 |    0   |     0    |
|  ✅  | buildo/prisma                  |    0   |     0    |
|  ✅ | buildo/pledge                  |    0   |     0   |

**Comment by dhinus** [comment]
💯 
I also tested it on the contactlab repos (added to master in #100 but not tested in this PR), no errors.

**Pull request merged**
