### PR TITLE
#60: [Rules] Add max-len rule (closes #60)

### LINKED ISSUE #60: [Rules] Add max-len rule
## requirements

We should add the rule to lint very long lines.
The default value for code line is `80`, which could be fine (to test before) and comments are configurable.
## specs
- [eslint max-len](http://eslint.org/docs/rules/max-len)
## misc

{optional: other useful info}

c/c @buildo/frontend

### PR DESCRIPTION
**Pull request by ascariandrea**
Issue #60
### tests performed

I've run the lint on the lol web project and here are the result!

screen shot 2016-05-20 at 14 28 51

### CODE REVIEW

**Comment by gabro** [comment]
a bit too much? Are sure we want to merge this with projects in this state? @buildo/frontend

**Comment by giogonzo** [comment]
no, not sure, and as already pointed out I think 100 is too low :P

no --fix and no jscodeshift makes this even more painful

**Comment by gabro** [comment]
too low compared to what?
The purpose of a line limit is to keep code readable on various devices. More than 100 means you always have a "normal" computer and you don't have split views.

I think 100 is reasonable for working with split screens and reviewing from mobile.

**Comment by giogonzo** [comment]
too low respect to how current code is formatted :P but if everyone agrees on the number I'm ok with 100 and it is just a matter of fixing projects => need to define guidelines for wrapping/indenting/multiline (but this is another story)

mobile is out of scope here, as it would require lines < 40/50 characters I think
about split views, not really used to work with more than 2 code splits (+ editor wrap), so no real opinion

**Comment by gabro** [comment]
github mobile landscape is 80 characters ;)

two split screens + sidebar is baaad on my 15"

image

(first panel is exactly 100 wide, look at the second panel)

**Comment by gabro** [comment]
Anyway, I'm generally fine with 100, but I'm not merging this without knowing the name of the person who's going to make sure this gets backported to existing projects.
I can do it for ipercron, anyone else? @buildo/frontend?

**Comment by ascariandrea** [comment]
Lexdoit is up to me!

And I imagine:
Oxway => @FrancescoCioria
Laboline => @francescogior 
Hailadoc => me ? @giogonzo ?

**Comment by francescogior** [comment]
🐢

**Comment by FrancescoCioria** [comment]
oxway is not using `eslint` yet (last time I tried I had 3000+ errors and I gave up)

**Comment by gabro** [comment]
If @francescogior is ok with labonline, I'm going to merge this.

**Comment by francescogior** [comment]
OK!

**Comment by gabro** [comment]
your dicks
_cazzi vostri_

**Pull request merged**
