### PR TITLE
[WIP] Descriptive style guide, airbnb style

### PR DESCRIPTION
**Pull request by gabro**
I think explaining our choices is valuable, both to us and to a general public.

I've started copying over from airbnb's guide what make sense for us. Still WIP, but take a look, @buildo/frontend

### CODE REVIEW

**Comment by gabro** [comment]
Actually, this might be better served as a gitbook. I'll give it a try later.

**Comment by gabro** [comment]
Not sure of why pdf/mobi/epub are failing, but still: https://buildo.gitbooks.io/js-style-guide/content/guide/01.Types.html

doesn't look bad!

**Comment by FrancescoCioria** [comment]
:+1: 
I think most of these rules/conventions are already accepted and in use at buildo, still having them written down will definitely be useful. One simple ex: we hire someone -> we get them to read this :)

**Comment by nerder** [comment]
As a point of view of a new entry, this is just great! It helps a lot understand conventions, and how things have to be done. We should explain why we use `no-loop-func` or is just to broad?

Note: i saw a short explaination at 7.2 but it can be extended IMO, that was the hardest part to get to me.

**Comment by gabro** [comment]
Yup, this is meant for newcomers, or people not familiar with our coding style in general.

Currently I'm just copying over whatever makes sense from airbnb/javascript, then I'll add new stuff specific to buildo, so yes, `no-loop-func` will be explained!

Thanks for the feedback

**Comment by gabro** [comment]
wishful thinking. Closing for now.

**Pull request closed without merging**
